AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: TripSage AWS resources

Parameters:
  ResourceEnv:
    Description: 'Environment which the resources will be deployed to'
    Type: 'String'
    AllowedValues:
      - 'dev'
      - 'prod'

  ServiceEnv:
    Description: 'Name of the service environment'
    Type: 'String'

  LogLevel:
    Description: "Log level for functions"
    Type: String
    Default: 'INFO'
    AllowedValues:
      - 'INFO'
      - 'DEBUG'

Conditions:
  IsProdDeployment: !Equals [!Ref ServiceEnv, 'prod']

Globals:
  Function:
    Runtime: python3.10
    Timeout: 180
    Environment:
      Variables:
        LOG_LEVEL:
          Ref: LogLevel
        ResourceEnv: !Ref ResourceEnv
        ServiceEnv: !Ref ServiceEnv

Resources:
###############
#  S3 BUCKET  #
###############

  TripSageBucket:
    Type: AWS::S3::Bucket
    Condition: IsProdDeployment
    Properties:
      BucketName: !Sub tripsage.net

####################
#  DYNAMODB TABLE  #
####################

  TripSageDdbTableDev:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: TripSage-Dev
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: GSI1_PK
          AttributeType: S
        - AttributeName: GSI1_SK
          AttributeType: S
        - AttributeName: GSI2_PK
          AttributeType: S
        - AttributeName: GSI2_SK
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: GSI1
          KeySchema:
            - AttributeName: GSI1_PK
              KeyType: HASH
            - AttributeName: GSI1_SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: GSI2
          KeySchema:
            - AttributeName: GSI2_PK
              KeyType: HASH
            - AttributeName: GSI2_SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  TripSageDdbTableProd:
    Type: AWS::DynamoDB::Table
    Condition: IsProdDeployment
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: TripSage-Prod
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: GSI1_PK
          AttributeType: S
        - AttributeName: GSI1_SK
          AttributeType: S
        - AttributeName: GSI2_PK
          AttributeType: S
        - AttributeName: GSI2_SK
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: GSI1
          KeySchema:
            - AttributeName: GSI1_PK
              KeyType: HASH
            - AttributeName: GSI1_SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: GSI2
          KeySchema:
            - AttributeName: GSI2_PK
              KeyType: HASH
            - AttributeName: GSI2_SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

####################
#  SSM Parameters  #
####################

  # DynamoDbName:
  #   Type: AWS::SSM::Paramter
  #   Properties:
  #     Description: "Trip Sage DDB Name"
  #     Name: !Sub "TripSageDdbName-${ResourceEnv}"
  #     Type: "String"
  #     Value:
  #       - !Ref TripSageDdbTableDev
  #       - !Ref TripSageDdbTableProd
  
  # DynamoDbArn:
  #   Type: AWS::SSM::Parameter
  #   Properties:
  #     Description: "Trip Sage DDB Arn"
  #     Name: !Sub "TripSageDdbArn-${ResourceEnv}"
  #     Type: "String"
  #     Value:
  #       - !Ref TripSageDdbTableDev.Arn
  #       - !Ref TripSageDdbTableProd.Arn
  
#############
#  OUTPUTS  #
#############