AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: TripSage AWS resources

Parameters:
  ResourceEnv:
    Description: 'Environment which the resources will be deployed to'
    Type: 'String'
    AllowedValues:
      - 'dev'
      - 'prod'

  ServiceEnv:
    Description: 'Name of the service environment'
    Type: 'String'

  LogLevel:
    Description: "Log level for functions"
    Type: String
    Default: 'INFO'
    AllowedValues:
      - 'INFO'
      - 'DEBUG'

Conditions:
  IsProdDeployment: !Equals [!Ref ResourceEnv, 'prod']

Globals:
  Function:
    Runtime: python3.10
    Timeout: 180
    Environment:
      Variables:
        LOG_LEVEL:
          Ref: LogLevel
        ResourceEnv: !Ref ResourceEnv
        ServiceEnv: !Ref ServiceEnv

Resources:
###############
#  S3 BUCKET  #
###############

  TripSageBucket:
    Type: AWS::S3::Bucket
    Condition: IsProdDeployment
    Properties:
      BucketName: !Sub tripsage.net
  
#############
#  OUTPUTS  #
#############