# Generated by Django 4.2.3 on 2023-08-04 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='start_datetime',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
