# Generated by Django 4.2.3 on 2023-08-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_attraction_start_datetime_alter_itinerary_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='start_datetime',
            field=models.DateTimeField(),
        ),
    ]
