# Generated by Django 4.2.3 on 2023-08-06 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_attraction_start_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='type',
        ),
        migrations.AddField(
            model_name='flight',
            name='airline',
            field=models.CharField(default='N/A', max_length=200),
        ),
    ]
