# Generated by Django 4.2.3 on 2023-08-06 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_flight_type_flight_airline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='airline',
            field=models.CharField(max_length=200),
        ),
    ]
