# Generated by Django 4.2.3 on 2023-08-09 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_flight_airline'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='type',
            field=models.CharField(choices=[('departing', 'departing'), ('return', 'return')], default='departing', max_length=10),
        ),
    ]
