# Generated by Django 4.2.3 on 2023-08-09 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_flight_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='type',
            field=models.CharField(choices=[('departing', 'departing'), ('return', 'return')], max_length=10),
        ),
    ]
