name: Dev Env - Feature, Hotfix, Bugfix
on:
  push:
    branches-ignore:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v3
      
      - name: cfn-lint
        run: |
          pip3 install cfn-lint
          cfn-lint template.yml
      
  deploy:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-role
          role-session-name: github-actions
          aws-region: us-east-1
      
      - name: Install Sam
        run: |
          pip3 install aws-sam-cli
      
      - name: Sam build
        run: |
          sam build

      - name: Sam Deploy
        run: |
          branch_name="$GITHUB_REF_NAME"
          github_branch_name=$(echo "$branch_name" | tr '/' '-')
          echo "$converted_branch_name"
          sam deploy --stack-name "$github_branch_name" --s3-bucket tripsage-sam-bucket --s3-prefix "$converted_branch_name" --region us-east-1 --parameter-overrides DeploymentEnv="dev-feature" ResourceEnv="dev" 